builds:
-
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
  env:
    - GO111MODULE=on
    - CGO_ENABLED=0
  main: ./main.go
  binary: kushtakad

before:
  hooks:
    - go mod download
    - packr2 clean
    - packr2
      
checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-alpha"

changelog:
  sort: asc

archives:
  - id: kushtakad
    format: gz
    format_overrides:
      - goos: windows
        format: zip
    files:
    - none*
