##
## BUILDS
## 
builds:
##
## kushtakad
##
- id: kushtakad
  main: ./main.go
  binary: kushtakad
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
  env:
    - GO111MODULE=on
    - CGO_ENABLED=0

  ldflags:
    - -s -w -X main.version={{.Version}} -X github.com/kushtaka/kushtakad/version.current={{.Version}}
##
## BEFORE
## 
before:
  hooks:
    - go mod download
    - packr2 clean
    - packr2
      
checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}"

changelog:
  sort: asc

##
## ARCHIVES
##
archives:
  ##
  ## kushtakad
  ##
  - id: kushtakad
    builds:
    - kushtakad
    format: gz
    format_overrides:
      - goos: windows
        format: zip
    files:
    - none*

##
## SNAPS
##
snapcrafts:
  - id: kushtakad

    name: kushtakad
    summary: Kushtakad act as either a server or sensor 
    description: Kushtaka.io is a sustainable all-in-one honeypot and honeytoken orchestrator for under-resourced Blue Teams. 
    license: Apache-2.0
    publish: false
    base: core18
    grade: devel
    confinement: devmode # devmode, strict, classic
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      amd64: 64-bit
      darwin: macOS
      linux: Tux

    apps:
      conf:
      sensor:
        plugs: ["network", "network-bind"]
        daemon: simple
        args: -sensor
      server:
        plugs: ["network", "network-bind"]
        daemon: simple
        args: -server

##
## NFPMS
##

# .goreleaser.yml
nfpms:
  # note that this is an array of nfpm configs
  -
    # ID of the nfpm config, must be unique.
    # Defaults to "default".
    id: kushtakad

    # Name of the package.
    # Defaults to `ProjectName`.
    package_name: kushtakad

    # You can change the file name of the package.
    # Default: `{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}`
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

    # Build IDs for the builds you want to create NFPM packages for.
    # Defaults to all builds.
    builds:
    - kushtakad

    # Replacements for GOOS and GOARCH in the package name.
    # Keys should be valid GOOSs or GOARCHs.
    # Values are the respective replacements.
    # Default is empty.
    replacements:
      amd64: 64-bit
      386: 32-bit
      darwin: macOS
      linux: Tux

    # Your app's vendor.
    # Default is empty.
    vendor: kushtaka
    # Your app's homepage.
    # Default is empty.
    homepage: https://kushtaka.io/

    # Your app's maintainer (probably you).
    # Default is empty.
    maintainer: Jared Folkins <jfolkins@gmail.com>

    # Your app's description.
    # Default is empty.
    description: Kushtaka.io is a sustainable all-in-one honeypot and honeytoken orchestrator for under-resourced Blue Teams. 

    # Your app's license.
    # Default is empty.
    license: Proprietary

    # Formats to be generated.
    formats:
      - deb
      - rpm

    # Override default /usr/local/bin destination for binaries
    bindir: /kushtaka

    # Package epoch.
    # Defaults to empty.
    epoch: 1

    # Empty folders that should be created and managed by the packager
    # implementation.
    # Default is empty.
    empty_folders:
    - /kushtaka
