##
## BUILDS
## 
builds:
##
## kushtakad
##
- id: kushtakad
  main: ./main.go
  binary: kushtakad
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
  env:
    - GO111MODULE=on
    - CGO_ENABLED=0

- id: kushtakad-server
  main: ./main.go
  binary: kushtakad-server
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
  env:
    - GO111MODULE=on
    - CGO_ENABLED=0

- id: kushtakad-sensor
  main: ./main.go
  binary: kushtakad-sensor
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
  env:
    - GO111MODULE=on
    - CGO_ENABLED=0

##
## BEFORE
## 
before:
  hooks:
    - go mod download
    - packr2 clean
    - packr2
      
checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-beta"

changelog:
  sort: asc

##
## ARCHIVES
##
archives:
  ##
  ## kushtakad
  ##
  - id: kushtakad
    builds:
    - kushtakad
    format: gz
    format_overrides:
      - goos: windows
        format: zip
    files:
    - none*

##
## SNAPS
##
snapcrafts:
  - id: kushtakad-server
    builds:
    - kushtakad-server

    name_template: "{{ .ProjectName }}_server_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

    replacements:
      amd64: 64-bit
      darwin: macOS
      linux: Tux

    name: kushtakad-server
    summary: Kushtakad Server
    description: Kushtaka.org is a sustainable all-in-one honeypot and honeytoken orchestrator for under-resourced Blue Teams. 

    license: Apache-2.0
    publish: false
    grade: beta
    confinement: strict
    #grade: edge
    #base: core18
    #confinement: classic
    apps:
      kushtakad-server:
        plugs: ["network", "network-bind"]
        daemon: simple

  - id: kushtakad-sensor
    builds:
    - kushtakad-sensor

    name_template: "{{ .ProjectName }}_sensor_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

    replacements:
      amd64: 64-bit
      darwin: macOS
      linux: Tux

    name: kushtakad-sensor
    summary: Kushtakad Sensor
    description: Kushtaka.org is a sustainable all-in-one honeypot and honeytoken orchestrator for under-resourced Blue Teams. 

    license: Apache-2.0
    publish: false
    grade: beta
    confinement: strict
    #base: core18
    #grade: edge
    #confinement: classic
    apps:
      kushtakad-sensor:
        plugs: ["network", "network-bind"]
        daemon: simple
        args: -sensor
